version: "3"

vars:
  SHELL: zsh
  FLAKE_URL: git+https://github.com/suvanshenoy/nix-flakes?dir=ex

tasks:
  setup:
    cmds:
      - "nix develop --no-write-lock-file {{.FLAKE_URL}} --command {{.SHELL}}"
      - mix setup

  dev:
    cmds:
      - mix phx.server

  prod:
    dotenv:
      - .env
    cmds:
      - mix release
      - ./_build/prod/rel/ghostvault/bin/ghostvault start
