version: "3"

vars:
  SHELL: zsh

tasks:
  nix:setup:
    cmds:
      - "nix develop --command {{.SHELL}}"
  mix:nix:dev:
    cmds:
      - "nix run github:nix-community/nixGL#nixGLIntel -- mix run --no-halt"

  mix:dev:
    cmds:
      - mix run --no-halt
